### ISSUE TITLE
Web Generation produces large files

### ISSUE THREAD

**Issue by firedfly** [harlam357/hfm-net#349]
I noticed the web generation output produces large files when a slot does not have an active WU.  I just had several GPUs fail to get new work (WU shortage) and the SlotSummary.xml grew from ~200kb to just under 8mb.  The increased size appears to be due to many more log lines being included in the output.  The slot specific xml files have this same issue.  I'm not producing html or log files, but I expect they would have the same problem.

Is it possible to limit the number of log lines output for a slot that doesn't have an active work unit?  Let me know if you need any other information.

**Comment by firedfly** [comment]
@harlam357  If you have guidance on how you'd like this addressed, I can look into making the code changes.  My thought was to limit the output to 200 log lines per slot

**Comment by harlam357** [comment]
When a slot has no current WU the logic will fall back to providing the entire log for the slot or the client.  This doesn't impact the UI because the log viewer control itself has a limit on how many lines are displayed.  I think it's 500.  Check LogViewer.cs.  if you want to implement I suggest making the change in the XML generation code.
